import SyntaxHighlighter from 'react-syntax-highlighter';
import { anOldHope, stackoverflowDark } from 'react-syntax-highlighter/dist/esm/styles/hljs';
import Clipboard from '@/components/Clipboard';
import MenuButton from '@/icons/MenuButton';
import BracesAsterisk from '@/icons/BracesAsterisk';
import ArrowRight from '@/icons/ArrowRight';

const Components = () => {
  const code_quickly = `
  <ul class="nav nav-pills nav-fill gap-2 p-1 small bg-primary rounded-5 shadow-sm" id="pillNav2" role="tablist" style="--bs-nav-link-color: var(--bs-white); --bs-nav-pills-link-active-color: var(--bs-primary); --bs-nav-pills-link-active-bg: var(--bs-white);">
    <li class="nav-item" role="presentation">
      <button class="nav-link active rounded-5" id="home-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="true">Home</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link rounded-5" id="profile-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="false">Profile</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link rounded-5" id="contact-tab2" data-bs-toggle="tab" type="button" role="tab" aria-selected="false">Contact</button>
    </li>
  </ul>
  `
  const code_create = `
  @import "bootstrap/scss/bootstrap";

  $utilities: map-merge(
    $utilities,
    (
      "cursor": (
        property: cursor,
        class: cursor,
        responsive: true,
        values: auto pointer grab,
      )
    )
  );
  `
  return (
    <section className="max-w-[1320px] w-full px-6 mx-auto mb-12 pb-12">
      <div className="w-full mb-12
      lg:w-7/12">
        <div className="flex items-center gap-2 mb-4">
          <div className="bg-red-800/15 p-4 inline-block rounded-2xl">
            <MenuButton className={"w-10 h-10 text-red-500"}/>
          </div>
          <div className="text-4xl font-extralight w-8 h-8 flex justify-center items-center">
            +
          </div>
          <div className="bg-emerald-800/15 p-4 inline-block rounded-2xl">
            <BracesAsterisk className={"w-10 h-10 text-emerald-300"}/>
          </div>
        </div>
        <h2 className="text-3xl font-bold mb-4
        md:text-4xl
        lg:text-5xl">Components, meet the Utility API</h2>
        <p className="text-base mb-4 md:text-xl">New in Bootstrap 5, our utilities are now generated by our <a href="#" className="text-blue-400 underline hover:brightness-125">Utility API</a>. We built it as a feature-packed Sass map that can be quickly and easily customized. It's never been easier to add, remove, or modify any utility classes. Make utilities responsive, add pseudo-class variants, and give them custom names.</p>
      </div>

      <div className="grid grid-cols-2 gap-12">
        <div className="mb-4 col-span-2
        lg:col-span-1">
          <h3 className="text-xl mb-2 font-semibold md:text-2xl lg:text-3xl">Quickly customize components</h3>
          <p className="mb-4">Apply any of our included utility classes to our components to customize their appearance, like the navigation example below. There are hundreds of classes available—from <a href="#" className="text-blue-400 underline hover:brightness-125">positioning</a> and <a href="#" className="text-blue-400 underline hover:brightness-125">sizing</a> to <a href="#" className="text-blue-400 underline hover:brightness-125">colors</a> and <a href="#" className="text-blue-400 underline hover:brightness-125">effects</a>. Mix them with CSS variable overrides for even more control.</p>

          <div className="text-base rounded-md mb-6 p-6 border border-gray-600 bg-transparent">
            <div className="mb-6 flex ">
              <div className=' rounded-md overflow-hidden'>
                <input type="radio" className="peer hidden" id="r-home" name="radio-1" defaultChecked="true"/>
                <label
                  className="text-blue-400 px-4 py-2 rounded-md hover:text-blue-300 peer-checked:bg-blue-600 peer-checked:text-white inline-block cursor-pointer"
                  htmlFor="r-home"
                >
                  Home
                </label>
              </div>

              <div>
                <input type="radio" className="peer hidden" id="r-profile" name="radio-1"/>
                <label
                  className="text-blue-400 px-4 py-2 rounded-md hover:text-blue-300 peer-checked:bg-blue-600 peer-checked:text-white inline-block cursor-pointer"
                  htmlFor="r-profile"
                >
                  Profile
                </label>
                </div>

              <div>
                <input type="radio" className="peer hidden" id="r-contact" name="radio-1"/>
                <label
                  className="text-blue-400 px-4 py-2 rounded-md hover:text-blue-300 peer-checked:bg-blue-600 peer-checked:text-white inline-block cursor-pointer"
                  htmlFor="r-contact"
                  >
                  Contact
                </label>
              </div>
            </div>

            <div className="mb-0 flex w-full bg-blue-600 rounded-full overflow-hidden items-center">
              <div className='flex-1 p-1'>
                <input type="radio" className="peer hidden" id="r-home2" name="radio-2" defaultChecked="true"/>
                <label
                  className="text-blue-400 px-4 py-2 hover:text-blue-300 peer-checked:bg-white peer-checked:text-blue-600 inline-block w-full text-center rounded-full cursor-pointer"
                  htmlFor="r-home2"
                  >
                  Home
                </label>
              </div>
              
              <div className='flex-1 p-1'>
                <input type="radio" className="peer hidden" id="r-profile2" name="radio-2"/>
                <label
                  className="text-blue-400 px-4 py-2 hover:text-blue-300 peer-checked:bg-white peer-checked:text-blue-600 inline-block w-full text-center rounded-full cursor-pointer"
                  htmlFor="r-profile2"
                >
                  Profile
                </label>
                </div>

              <div className='flex-1 p-1'>
                <input type="radio" className="peer hidden" id="r-contact2" name="radio-2"/>
                <label
                  className="text-blue-400 px-4 py-2 hover:text-blue-300 peer-checked:bg-white peer-checked:text-blue-600 inline-block w-full text-center rounded-full cursor-pointer"
                  htmlFor="r-contact2"
                >
                  Contact
                </label>
              </div>
            </div>
          </div>
          <div className="text-sm rounded-md mb-4 overflow-hidden border border-gray-600 flex justify-between bg-[#1c1c21] w-screen -ml-6
          md:w-full md:ml-0">
            <SyntaxHighlighter language='htmlbars' style={stackoverflowDark}>
              {code_quickly}
            </SyntaxHighlighter>
            <div className='flex items-center'>
              <Clipboard content={code_quickly}/>
            </div>
          </div>

          <div className="group font-semibold text-blue-400 inline-flex items-center">
            <div className="group-hover:brightness-125 group-hover:cursor-pointer underline underline-offset-4">
              Explore customized components
            </div>
            <ArrowRight className={"inline-block w-5 h-5 ml-1 group-hover:translate-x-1 transition-transform"}/>
          </div>
        </div>
        <div className="mb-4 col-span-2
        lg:col-span-1">
          <h3 className="text-xl mb-2 font-semibold md:text-2xl lg:text-3xl">Create and extend utilities</h3>
          <p className="mb-4">Use Bootstrap's utility API to modify any of our included utilities or create your own custom utilities for any project. Import Bootstrap first, then use Sass map functions to modify, add, or remove utilities.</p>

          <div className="text-sm rounded-md mb-4 overflow-hidden border border-gray-600 flex justify-between bg-[#1c1c21] w-screen -ml-6 md:w-full md:ml-0">
            <SyntaxHighlighter language='scss' style={anOldHope}>
              {code_create}
            </SyntaxHighlighter>
            <div className='flex items-center'>
              <Clipboard content={code_create}/>
            </div>
          </div>

          <div className="group font-semibold text-blue-400 inline-flex items-center">
            <div className="group-hover:brightness-125 group-hover:cursor-pointer underline underline-offset-4">
              Explore the utility API
            </div>
            <ArrowRight className={"inline-block w-5 h-5 ml-1 group-hover:translate-x-1 transition-transform"}/>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Components